apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-mqtt
namePrefix: test-

resources:
- ../../base

#components:
#- ../../variants/non-prod

patchesStrategicMerge:
- version.yaml
#- debug.yaml
